[workspace]
members = [ "state-wise-votes"
, "vote-percentage", "vote-splitting"]

resolver = "2"

[workspace.dependencies]
polars = { version = "0.40.0", features = ["lazy", "csv", "json"] }
serde = "1.0.203"
serde_json = "1.0.117"
